name: shipment_analytics
version: 1.0.0
config-version: 2
profile: shipment_analytics

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  shipment_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
